/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo V14 G2-ALC
 */
public class Beranda extends javax.swing.JFrame {
    
    public Statement st;
    public PreparedStatement ps;
    public ResultSet rs;
    Connection conn=Config.Koneksi.koneksiDB();
    NumberFormat angkakoma=NumberFormat.getIntegerInstance();
    
    public Beranda() {
        initComponents();
        showdataitem();
        noFaktur();
        tanggal();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Item = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_menu = new javax.swing.JTable();
        Transaksi = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txt_menu = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        txt_qty = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_transaksi = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_totalbayar = new javax.swing.JTextField();
        txt_tunai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_kembali = new javax.swing.JTextField();
        btn_bayar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btm_tambahitem = new javax.swing.JButton();
        lb_faktur = new javax.swing.JTextField();
        lb_tgl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(0, 0, 0));

        Header.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setText("APLIKASI KASIR");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(570, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(544, 544, 544))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        Item.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Cari Item");

        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        tbl_menu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Menu", "Kategori", "Harga"
            }
        ));
        tbl_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_menuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_menu);

        javax.swing.GroupLayout ItemLayout = new javax.swing.GroupLayout(Item);
        Item.setLayout(ItemLayout);
        ItemLayout.setHorizontalGroup(
            ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_cari)
                .addContainerGap())
            .addGroup(ItemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ItemLayout.setVerticalGroup(
            ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Transaksi.setBackground(new java.awt.Color(204, 204, 204));

        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        txt_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_qtyKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reset)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_add)
                    .addComponent(btn_reset)
                    .addComponent(txt_qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Faktur", "Tanggal", "Menu", "Quantity", "Harga", "Jumlah"
            }
        ));
        tbl_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_transaksiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_transaksi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Total Bayar");

        txt_totalbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalbayarActionPerformed(evt);
            }
        });

        txt_tunai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_tunaiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tunaiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_tunaiKeyTyped(evt);
            }
        });

        jLabel3.setText("Cash");

        jLabel4.setText("Kembali");

        txt_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kembaliActionPerformed(evt);
            }
        });

        btn_bayar.setText("Bayar");
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_totalbayar)
                    .addComponent(txt_tunai)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_kembali))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(btn_bayar)
                .addGap(56, 56, 56))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_totalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_tunai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_bayar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btm_tambahitem.setText("Tambah Item");
        btm_tambahitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_tambahitemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btm_tambahitem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btm_tambahitem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lb_faktur.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_faktur.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lb_faktur.setText("FAKTUR");
        lb_faktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb_fakturActionPerformed(evt);
            }
        });

        lb_tgl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_tgl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lb_tgl.setText("TANGGAL");
        lb_tgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb_tglActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("No. Faktur");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tanggal");

        javax.swing.GroupLayout TransaksiLayout = new javax.swing.GroupLayout(Transaksi);
        Transaksi.setLayout(TransaksiLayout);
        TransaksiLayout.setHorizontalGroup(
            TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(TransaksiLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TransaksiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_faktur, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_tgl)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(193, 193, 193))
        );
        TransaksiLayout.setVerticalGroup(
            TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_faktur, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addComponent(Item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Item, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        DefaultTableModel model=(DefaultTableModel)tbl_transaksi.getModel();
        
        if (txt_menu.getText().equals("")||txt_harga.getText().equals("")||txt_qty.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Gagal menambahkan barang!", "Peringatan",JOptionPane.WARNING_MESSAGE);
        }else{
            String noFaktur = lb_faktur.getText();
            String tanggal = lb_tgl.getText();
            String menu = txt_menu.getText();
            int qty = Integer.parseInt(txt_qty.getText());
            String harga = txt_harga.getText();
            String ReplaceHarga = harga.replaceAll(",", "");
            int jumlah = qty * Integer.parseInt(ReplaceHarga);
            
            Object[] RowData={noFaktur,tanggal,menu,qty,harga,angkakoma.format(jumlah)};
            model.addRow(RowData);
            HitungTotal();
            txt_menu.setText("");
            txt_harga.setText("");
            txt_qty.setText("");
            txt_cari.setText("");
            txt_cari.requestFocus();
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kembaliActionPerformed

    private void lb_fakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb_fakturActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_fakturActionPerformed

    private void lb_tglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb_tglActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_tglActionPerformed

    private void tbl_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_menuMouseClicked
        DefaultTableModel model=(DefaultTableModel)tbl_menu.getModel();
        int SelectedRow=tbl_menu.getSelectedRow();
        String menu=model.getValueAt(SelectedRow, 0).toString();
        String harga=model.getValueAt(SelectedRow, 2).toString();
        int qty=1;
        
        txt_menu.setText(menu);
        txt_harga.setText(String.valueOf(harga));
        txt_qty.setText(String.valueOf(qty));
        txt_qty.requestFocus();
    }//GEN-LAST:event_tbl_menuMouseClicked

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        showdataitem();
    }//GEN-LAST:event_txt_cariKeyReleased

    private void txt_totalbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalbayarActionPerformed

    private void txt_tunaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tunaiKeyTyped
        char validasiangka=evt.getKeyChar();
        if(!Character.isDigit(validasiangka)){
            evt.consume();
        }
    }//GEN-LAST:event_txt_tunaiKeyTyped

    private void txt_tunaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tunaiKeyReleased
        formatDesimal();
        if(txt_tunai.getText().isEmpty()){
            txt_kembali.setText("");
        }else{
            int cash=Integer.parseInt(txt_tunai.getText().replaceAll(",", ""));
            int totalbayar=Integer.parseInt(txt_totalbayar.getText().replaceAll(",", ""));
            int hasil=cash-totalbayar;
            
            if(cash >= totalbayar){
                String koma=angkakoma.format(hasil);
                txt_kembali.setText(String.valueOf(koma));
            }else{
                txt_kembali.setText("");
            }
        }
    }//GEN-LAST:event_txt_tunaiKeyReleased

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
        if(txt_kembali.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Anda belum memasukkan pembayawan","Validasi",JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                DefaultTableModel model=(DefaultTableModel)tbl_transaksi.getModel();
                for(int i=0;i<tbl_transaksi.getRowCount();i++){
                    String nofaktur=model.getValueAt(i, 0).toString();
                    String tgl=model.getValueAt(i, 1).toString();
                    String item=model.getValueAt(i, 2).toString();
                    String qty=model.getValueAt(i, 3).toString();
                    String harga=model.getValueAt(i, 4).toString();
                    String jumlah=model.getValueAt(i, 5).toString();
                    
                    String sql="INSERT INTO tbl_penjualan (no_faktur,tgl,item,qty,harga,jumlah) VALUES(?,?,?,?,?,?)";
                    ps=conn.prepareStatement(sql);
                    ps.setString(1,nofaktur);
                    ps.setString(2,tgl);
                    ps.setString(3,item);
                    ps.setString(4,qty);
                    ps.setString(5,harga);
                    ps.setString(6,jumlah);
                    ps.executeUpdate();
                }
                JOptionPane.showMessageDialog(this, "Transaksi berhasil","Pembayaran",JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            noFaktur();
        }
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        reset();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tbl_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_transaksiMouseClicked
        DefaultTableModel model=(DefaultTableModel)tbl_transaksi.getModel();
        int SelectedRow=tbl_transaksi.getSelectedRow();
        if(SelectedRow!=-1){
            int rowindexmodel=tbl_transaksi.convertRowIndexToModel(SelectedRow);
            model.removeRow(rowindexmodel);
        }
        HitungTotal();
    }//GEN-LAST:event_tbl_transaksiMouseClicked

    private void txt_qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtyKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            DefaultTableModel model=(DefaultTableModel)tbl_transaksi.getModel();
        
            if (txt_menu.getText().equals("")||txt_harga.getText().equals("")||txt_qty.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Gagal menambahkan barang!", "Peringatan",JOptionPane.WARNING_MESSAGE);
            }else{
                String noFaktur = lb_faktur.getText();
                String tanggal = lb_tgl.getText();
                String menu = txt_menu.getText();
                int qty = Integer.parseInt(txt_qty.getText());
                String harga = txt_harga.getText();
                String ReplaceHarga = harga.replaceAll(",", "");
                int jumlah = qty * Integer.parseInt(ReplaceHarga);

                Object[] RowData={noFaktur,tanggal,menu,qty,harga,angkakoma.format(jumlah)};
                model.addRow(RowData);
                HitungTotal();
                txt_menu.setText("");
                txt_harga.setText("");
                txt_qty.setText("");
                txt_cari.setText("");
                txt_cari.requestFocus();
            }
        }
    }//GEN-LAST:event_txt_qtyKeyPressed

    private void txt_tunaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tunaiKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(txt_kembali.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Anda belum memasukkan pembayawan","Validasi",JOptionPane.WARNING_MESSAGE);
            }else{
                try {
                    DefaultTableModel model=(DefaultTableModel)tbl_transaksi.getModel();
                    for(int i=0;i<tbl_transaksi.getRowCount();i++){
                        String nofaktur=model.getValueAt(i, 0).toString();
                        String tgl=model.getValueAt(i, 1).toString();
                        String item=model.getValueAt(i, 2).toString();
                        String qty=model.getValueAt(i, 3).toString();
                        String harga=model.getValueAt(i, 4).toString();
                        String jumlah=model.getValueAt(i, 5).toString();

                        String sql="INSERT INTO tbl_penjualan (no_faktur,tgl,item,qty,harga,jumlah) VALUES(?,?,?,?,?,?)";
                        ps=conn.prepareStatement(sql);
                        ps.setString(1,nofaktur);
                        ps.setString(2,tgl);
                        ps.setString(3,item);
                        ps.setString(4,qty);
                        ps.setString(5,harga);
                        ps.setString(6,jumlah);
                        ps.executeUpdate();
                    }
                    JOptionPane.showMessageDialog(this, "Transaksi berhasil","Pembayaran",JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                noFaktur();
            }
        }
    }//GEN-LAST:event_txt_tunaiKeyPressed

    private void btm_tambahitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_tambahitemActionPerformed
        Data_Item dataitem = new Data_Item();
        dataitem.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btm_tambahitemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Item;
    private javax.swing.JPanel Transaksi;
    private javax.swing.JButton btm_tambahitem;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_bayar;
    private javax.swing.JButton btn_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lb_faktur;
    private javax.swing.JTextField lb_tgl;
    private javax.swing.JTable tbl_menu;
    private javax.swing.JTable tbl_transaksi;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_kembali;
    private javax.swing.JTextField txt_menu;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_totalbayar;
    private javax.swing.JTextField txt_tunai;
    // End of variables declaration//GEN-END:variables
    
    private void showdataitem() {
        DefaultTableModel model=(DefaultTableModel)tbl_menu.getModel();
        model.setRowCount(0);
        String carimenu=txt_cari.getText();
        try {
            String sql="SELECT * FROM tbl_dataitem WHERE INSTR(nama_item,'"+ carimenu +"')>0";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery(sql);
            while(rs.next()) {
                int no=rs.getInt("No");
                String nama=rs.getString("nama_item");
                String kategori=rs.getString("kategori");
                int harga=rs.getInt("harga");

                Object[] RowData={nama,kategori,angkakoma.format(harga)};
                model.addRow(RowData);
            }
        } catch (Exception e) {
        }
    }
    
    private void HitungTotal(){
        int tot=0;
        for(int i=0;i<tbl_transaksi.getRowCount();i++){
            tot=tot+Integer.parseInt(tbl_transaksi.getValueAt(i, 5).toString().replaceAll(",", ""));
        }
        txt_totalbayar.setText(String.valueOf(angkakoma.format(tot)));
    }
    
    private void formatDesimal(){
        if(!txt_tunai.getText().isEmpty()){
            String ReplaceTunai=txt_tunai.getText().replaceAll("[^\\d]", "");
            double FormatDec=Double.parseDouble(ReplaceTunai);
            DecimalFormat decimalformat=new DecimalFormat("#,###,###");
            txt_tunai.setText(decimalformat.format(FormatDec));
            return;
        }
    }
    
    private void noFaktur(){
        String sql="SELECT MAX(no_faktur) FROM tbl_penjualan";
        try {
            st=conn.createStatement();
            rs=st.executeQuery(sql);
            rs.next();
            rs.getString("MAX(no_faktur)");
            if(rs.getString("MAX(no_faktur)")==null){
                lb_faktur.setText("INV00001");
            }else{
                long InvAngka=Long.parseLong(rs.getString("MAX(no_faktur)").substring(3,rs.getString("MAX(no_faktur)").length()));
                InvAngka++;
                lb_faktur.setText("INV"+String.format("%05d", InvAngka));
            }
        } catch (Exception e) {
        }
    }
    
    private void tanggal(){
        java.util.Date tgl = new java.util.Date();
        SimpleDateFormat FormatTanggal = new SimpleDateFormat("dd-MM-yyyy",Locale.getDefault());
        String TanggalSekarang = FormatTanggal.format(tgl);
        lb_tgl.setText(TanggalSekarang);
    }
    
    private void reset(){
        DefaultTableModel model=(DefaultTableModel)tbl_transaksi.getModel();
        model.setRowCount(0);
        txt_menu.setText("");
        txt_harga.setText("");
        txt_qty.setText("");
        txt_totalbayar.setText("");
        txt_tunai.setText("");
        txt_tunai.setText("");
        txt_kembali.setText("");
    }
}
